//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_vs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesafioDBEntities : DbContext
    {
        public DesafioDBEntities()
            : base("name=DesafioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estado_invitacion> Estado_invitacion { get; set; }
        public virtual DbSet<Invitados> Invitados { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Reunion> Reunion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
