//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_vs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitados
    {
        public int id_invitado { get; set; }
        public int id_usuario_e { get; set; }
        public int id_reunion_e { get; set; }
        public int id_estado_inv { get; set; }
    
        public virtual Estado_invitacion Estado_invitacion { get; set; }
        public virtual Reunion Reunion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
